export enum authConstants {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SIGNUP = 'SIGNUP',
  GET_ME = 'GET_ME'
}
export enum authSuccessConstants {
  LOGIN = 'LOGIN_SUCCESS',
  LOGOUT = 'LOGOUT_SUCCESS',
  SIGNUP = 'SIGNUP_SUCCESS',
  GET_ME = 'GET_ME_SUCCESS'
}
export enum authFailureConstants {
  LOGIN = 'LOGIN_FAILURE',
  LOGOUT = 'LOGOUT_FAILURE',
  SIGNUP = 'SIGNUP_FAILURE',
  GET_ME = 'GET_ME_FAILURE'
}
export enum bookmarkConstants {
  CREATE = 'CREATE_BOOKMARK',
  READ = 'READ_BOOKMARK',
  DELETE = 'DELETE_BOOKMARK',
  PATCH = 'PATCH_BOOKMARK',
  TOGGLE = 'TOGGLE_BOOKMARK',
  CHANGE_DETAILS = 'CHANGE_DETAILS_BOOKMARK'
}
export enum bookmarkSuccessConstants {
  CREATE = 'CREATE_SUCCESS_BOOKMARK',
  READ = 'READ_SUCCESS_BOOKMARK',
  DELETE = 'DELETE_SUCCESS_BOOKMARK',
  PATCH = 'PATCH_SUCCESS_BOOKMARK',
  TOGGLE = 'TOGGLE_SUCCESS_BOOKMARK',
  CHANGE_DETAILS = 'CHANGE_DETAILS_SUCCESS_BOOKMARK'
}
export enum bookmarkFailureConstants {
  CREATE = 'CREATE_FAILURE_BOOKMARK',
  READ = 'READ_FAILURE_BOOKMARK',
  DELETE = 'DELETE_FAILURE_BOOKMARK',
  PATCH = 'PATCH_FAILURE_BOOKMARK',
  TOGGLE = 'TOGGLE_FAILURE_BOOKMARK',
  CHANGE_DETAILS = 'CHANGE_DETAILS_FAILURE_BOOKMARK'
}
export enum folderConstants {
  CREATE = 'CREATE_FOLDER',
  READ = 'READ_FOLDER',
  READ_CHILDREN = 'READ_FOLDER_CHILDREN',
  UPDATE = 'UPDATE_FOLDER',
  DELETE = 'DELETE_FOLDER'
}
export enum folderSuccessConstants {
  CREATE = 'CREATE_SUCCESS_FOLDER',
  READ = 'READ_SUCCESS_FOLDER',
  READ_CHILDREN = 'READ_FOLDER_CHILDREN_SUCCESS',
  UPDATE = 'UPDATE_SUCCESS_FOLDER',
  DELETE = 'DELETE_SUCCESS_FOLDER',
  ADD_BID = 'ADD_BIDS_TO_FOLDER'
}
export enum folderFailureConstants {
  CREATE = 'CREATE_FAILURE_FOLDER',
  READ = 'READ_FAILURE_FOLDER',
  READ_CHILDREN = 'READ_FOLDER_CHILDREN_FAILURE',
  UPDATE = 'UPDATE_FAILURE_FOLDER',
  DELETE = 'DELETE_FAILURE_FOLDER'
}
