export enum authConstants {
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    SIGNIN = "SIGNIN",
    GETME = "GETME"
}
export enum authSucessConstants {
    LOGIN = "LOGIN_SUCCESS",
    LOGOUT = "LOGOUT_SUCCESS",
    SIGNIN = "SIGNIN_SUCCESS",
    GETME = "GETME_SUCCESS"
}
export enum authFaliureConstants {
    LOGIN = "LOGIN_FALIURE",
    LOGOUT = "LOGOUT_FALIURE",
    SIGNIN = "SIGNIN_FALIURE",
    GETME = "GETME_FALIURE"
}
export enum bookmarkConstants {
    CREATE = "CREATE_BOOKMARK",
    READ = "READ_BOOKMARK",
    DELETE = "DELETE_BOOKMARK",
    PATCH = "PATCH_BOOKMARK",
    TOGGLE = "TOGGLE_BOOKMARK",
    CHANGE_DETAILS = "CHANGE_DETAILS_BOOKMARK"
}
export enum bookmarkSucessConstants {
    CREATE = "CREATE_SUCCESS_BOOKMARK",
    READ = "READ_SUCCESS_BOOKMARK",
    DELETE = "DELETE_SUCCESS_BOOKMARK",
    PATCH = "PATCH_SUCCESS_BOOKMARK",
    TOGGLE = "TOGGLE_SUCCESS_BOOKMARK",
    CHANGE_DETAILS = "CHANGE_DETAILS_SUCCESS_BOOKMARK"
}
export enum bookmarkFaliureConstants {
    CREATE = "CREATE_FALIURE_BOOKMARK",
    READ = "READ_FALIURE_BOOKMARK",
    DELETE = "DELETE_FALIURE_BOOKMARK",
    PATCH = "PATCH_FALIURE_BOOKMARK",
    TOGGLE = "TOGGLE_FALIURE_BOOKMARK",
    CHANGE_DETAILS = "CHANGE_DETAILS_FALIURE_BOOKMARK"
}
export enum folderConstants {
    CREATE = "CREATE_FOLDER",
    READ = "READ_FOLDER",
    UPDATE = "UPDATE_FOLDER",
    DELETE = "DELETE_FOLDER",
}
export enum folderSucessConstants {
    CREATE = "CREATE_SUCCESS_FOLDER",
    READ = "READ_SUCCESS_FOLDER",
    UPDATE = "UPDATE_SUCCESS_FOLDER",
    DELETE = "DELETE_SUCCESS_FOLDER",
}
export enum folderFaliureConstants {
    CREATE = "CREATE_FALIURE_FOLDER",
    READ = "READ_FALIURE_FOLDER",
    UPDATE = "UPDATE_FALIURE_FOLDER",
    DELETE = "DELETE_FALIURE_FOLDER",
}